// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCollections(arg1) {
  return window['go']['main']['App']['GetCollections'](arg1);
}

export function GetCwd() {
  return window['go']['main']['App']['GetCwd']();
}

export function GoBack(arg1) {
  return window['go']['main']['App']['GoBack'](arg1);
}

export function ListFolders(arg1) {
  return window['go']['main']['App']['ListFolders'](arg1);
}
