// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateCollection(arg1:string):Promise<Error>;

export function DeleteCollection(arg1:string):Promise<Error>;

export function GetCollections(arg1:boolean):Promise<Array<string>>;

export function GetFaces(arg1:string):Promise<Array<string>>;

export function GetMatches(arg1:string):Promise<Array<string>>;

export function IndexFaces(arg1:string):Promise<Error>;

export function SaveMatches(arg1:string):Promise<Error>;

export function SearchFaces(arg1:string):Promise<Error>;
