// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateCollection(arg1:string):Promise<Error>;

export function DeleteCollection(arg1:string):Promise<Error>;

export function GetCollections(arg1:boolean):Promise<Array<string>>;

export function GetCwd():Promise<string>;

export function GoBack(arg1:string):Promise<string>;

export function IndexFaces(arg1:string,arg2:string):Promise<Error>;

export function ListFolders(arg1:string):Promise<Array<string>>;
