// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateCollection(arg1) {
  return window['go']['main']['App']['CreateCollection'](arg1);
}

export function DeleteCollection(arg1) {
  return window['go']['main']['App']['DeleteCollection'](arg1);
}

export function GetCollections(arg1) {
  return window['go']['main']['App']['GetCollections'](arg1);
}

export function GetFaces(arg1) {
  return window['go']['main']['App']['GetFaces'](arg1);
}

export function IndexFaces(arg1) {
  return window['go']['main']['App']['IndexFaces'](arg1);
}

export function SearchFaces(arg1) {
  return window['go']['main']['App']['SearchFaces'](arg1);
}
